version: '3'

services:
  rustbot:
    build: '.'
    env_file: '.env'
    restart: 'unless-stopped'
    volumes:
    - type: 'volume'
      source: 'rustbot-database'
      target: '/usr/src/app/database'


volumes:
  rustbot-database:
